<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $usersData = [
            [
                'id' => 1,
                'name' => 'المشرف الرئيسي',
                'email' => 'admin@gmail.com',
                'phone_1' => null,
                'phone_2' => null,
                'membership_level' => 'admin',
                'membership_no' => null,
                'membership_expire' => null,
                'contract_expire' => null,
                'contract_delay' => null,
                'contract_automatic_reactive' => '0',
                'estate' => '0',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'admin',
                'dark_mode' => 0,
                'remember_token' => 'XZq2Fb6VgzpLavTzYsBVXxUttO5y7JghL3eEQHPyR3iwxR6u9aD7zpOm0ZUJ',
                'created_at' => '2022-09-15 00:43:05',
                'updated_at' => '2023-03-12 14:55:13',
                'mobile_1'=>null,
                 'mobile_2'=>null,
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 5,
                'name' => 'المقيم',
                'email' => 'rater@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'rater',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'aabd-lrhmn-nbyla',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2022-09-15 02:30:06',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 6,
                'name' => 'مدخل البيانات',
                'email' => 'entre@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'entre',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'aabd-lrhmn-nbydsl',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2023-06-12 15:38:36',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 7,
                'name' => 'المنسق',
                'email' => 'coordinator@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'coordinator',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'aabd-lrhmn-nbfyl',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2023-06-12 16:04:01',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 8,
                'name' => 'المعاين',
                'email' => 'previewer@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'previewer',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => ',k',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2023-06-12 16:05:21',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 9,
                'name' => 'المراجع',
                'email' => 'reviewer@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'reviewer',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'aabd-lrhmn-nbryl',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2022-09-15 02:30:06',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 10,
                'name' => 'مدير المنشأة',
                'email' => 'manager@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'manager',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'er',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2023-06-12 15:53:21',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 11,
                'name' => 'مدير التقييم',
                'email' => 'rater_manager@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'rater_manager',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'aabd-lrhmn-nbyla',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2023-06-12 15:44:01',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 12,
                'name' => 'المعتمد',
                'email' => 'approver@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'approver',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI1',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'er',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2022-09-15 02:30:06',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 16,
                'name' => 'المعتمد لقيمة',
                'email' => 'qima_approver@gmail.com',
                'phone_1' => 'sd',
                'phone_2' => '+1 (121ds) 128-8696',
                'membership_level' => 'qima_approver',
                'membership_no' => 'J8fWhBHMPVi8t4xRdDuFtsQI12',
                'membership_expire' => '1987-12-09',
                'contract_expire' => '2018-03-14',
                'contract_delay' => '48',
                'contract_automatic_reactive' => '1',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$djietDTxmfExyjcJnURa2u2tlh3EcqRQYC8pCsJCRiMlIumzYg8LW',
                'active' => 1,
                'slug' => 'err',
                'dark_mode' => 0,
                'created_at' => '2022-09-15 02:08:22',
                'updated_at' => '2022-09-15 02:30:06',
                'mobile_1' => 'Sunt odit nostrud to',
                'mobile_2' => 'Quam nisi vero vel e',
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            [
                'id' => 15,
                'name' => 'محمد',
                'email' => 'info@7loll.net',
                'phone_1' => '01000000',
                'phone_2' => null,
                'membership_level' => 'client',
                'membership_no' => '6KYUrB5yiWMlMOb0KixJ3PzOC',
                'membership_expire' => null,
                'contract_expire' => null,
                'contract_delay' => null,
                'contract_automatic_reactive' => '0',
                'estate' => '1',
                'email_verified_at' => null,
                'password' => '$2y$10$1IuohJvvIb.i6VWgjJCL3erbkiFgoadGZB09XWGllDybSGOP5A9pm',
                'active' => 1,
                'slug' => 'mhmd',
                'dark_mode' => 0,
                'created_at' => '2023-06-03 05:52:18',
                'updated_at' => '2023-06-03 05:53:48',
                'mobile_1' => '540765936',
                'mobile_2' => null,
                 'name_en'=>null,
                 'member_number'=>null,
                 'identity' =>null,
                 'identity_number' =>null,
                 'member_date' =>null,
                'archive' => 0,
                'is_super_admin' => 0,
            ],
            // Add other users similarly
        ];
        foreach ($usersData as $userData) {
            User::create($userData);
        }
    }
}
